<?php

/**
 * @file
 * Provides an example address field lookup service.
 */

/**
 * Implements hook_addressfield_lookup_service_info().
 */
function addressfield_lookup_example_addressfield_lookup_service_info() {
  return array(
    'example' => array(
      'name' => t('Example'),
      'class' => 'AddressFieldLookupExample',
      'description' => t('Provides an example address field lookup service.'),
      'test data' => 'TS1 1ST',
    ),
  );
}

/**
 * Implements hook_addressfield_lookup_get_service_object().
 */
function addressfield_lookup_example_addressfield_lookup_get_service_object($class) {
  return new $class();
}
