<?php

/**
 * @file
 * Provides an example address field lookup service.
 */

/**
 * Implements hook_addressfield_lookup_service_info().
 */
function addressfield_lookup_example_addressfield_lookup_service_info() {
  return array(
    'example' => array(
      'name' => t('Example'),
      'class' => 'AddressFieldLookupExample',
      'object factory' => 'addressfield_lookup_example_create',
      'description' => t('Provides an example address field lookup service.'),
      'test data' => 'TS1 1ST',
    ),
  );
}

/**
 * Creates the example lookup service object.
 *
 * @return AddressFieldLookupInterface
 *   The instantiated lookup class.
 */
function addressfield_lookup_example_create($service_info) {
  return new $service_info['class']();
}
