<?php

/**
 * @file
 * Install/uninstall functions for tAddress Field Lookup Postcode Anywhere.
 */

/**
 * Implements hook_schema().
 */
function addressfield_lookup_postcodeanywhere_schema() {
  // Postcode anywhere country data cache.
  $schema['cache_addressfield_lookup_postcodeanywhere_country_data'] = drupal_get_schema_unprocessed('system', 'cache');

  return $schema;
}

/**
 * Implements hook_update_N().
 *
 * Create the country data cache table.
 */
function addressfield_lookup_postcodeanywhere_update_7000() {
  drupal_install_schema('addressfield_lookup_postcodeanywhere');
}
